-- BloomCraft starting data: the real product catalogue, coupons and the maker's admin e-mail.
-- Run after migrations/ (Supabase → SQL Editor). Re-running is safe: existing rows are kept.

-- The maker's login e-mail. Sign up / sign in with this address to open the Maker Studio.
insert into public.admin_emails (email) values ('vidhiisingh2403@gmail.com')
on conflict do nothing;

insert into public.products (
  id, slug, name, images, description, short_description, price, compare_at_price, category,
  keychain_type, tags, colors, availability, stock, max_qty_per_order, making_time_days,
  is_customizable, yarn_type, dimensions, stems_count, sort_order, created_at
) values
  ('cust-waist-chain', 'customized-waist-chain', 'Customized Waist Chain', array['/images/customized/custom_lace_collar_charm.jpg']::text[], 'Handcrafted delicate customized waist chain with intricate crochet lace detailing and artisan beads.', 'Handmade customized crochet waist chain', 25000, 30000, 'customized', null, array['Customized', 'Handmade', 'Bespoke']::text[], '[{"name":"Baby Pink & Gold","hex":"#FFB6C1"},{"name":"Pure White","hex":"#FFFFFF"}]'::jsonb, 'made_to_order', 10, 3, 3, true, '100% Premium Milk Cotton', 'Custom Fit', null, 0, '2026-01-01T10:00:00.000Z'),
  ('cust-bow-clip', 'customized-bow-clip', 'Customized Bow Clip', array['/images/customized/custom_crimson_mesh_bow.png']::text[], 'Artisan structured crochet bow clip with delicate lattice stitch and custom ribbon tails for hair or accessories.', 'Artisan structured crochet bow clip', 20000, 25000, 'customized', null, array['Customized', 'Hair Accessory', 'Handmade']::text[], '[{"name":"Crimson Wine","hex":"#8B0000"},{"name":"Pastel Blush","hex":"#FFB6C1"}]'::jsonb, 'made_to_order', 12, 5, 2, true, '100% Milk Cotton Yarn', '12 cm x 8 cm', null, 10, '2026-01-02T10:00:00.000Z'),
  ('cust-rakhi', 'customized-rakhi', 'Customized Rakhi', array['/images/customized/custom_rakhi.png']::text[], 'Exquisite set of 5 handcrafted floral crochet Rakhis with shimmering pearl beads on soft colored threads (Sunflower, Pink Blossom, White Daisy, Crimson Bloom, Sky Blue Rose).', 'Set of 5 handcrafted floral crochet Rakhis with pearl accents', 41000, 50000, 'customized', null, array['Customized', 'Festive', 'Handmade', 'Bestseller']::text[], '[{"name":"Assorted Floral Set of 5","hex":"#FFD700"},{"name":"Custom Color Palette","hex":"#FF69B4"}]'::jsonb, 'made_to_order', 20, 5, 2, true, '100% Soft Milk Cotton & Pearls', 'Standard wrist tie with adjustable thread', null, 20, '2026-01-04T10:00:00.000Z'),
  ('kc-tulip-pink-duo', 'baby-pink-double-tulip-bell-charm', 'Baby Pink Double Tulip Bell Charm', array['/images/keychains/tulip_pink_duo.jpg']::text[], 'Delicate soft pastel baby pink twin tulip bells crocheted with tender milk cotton yarn and leafy stem.', 'Pastel baby pink twin tulip charm', 10000, 12000, 'keychain', 'tulip', array['Pastel Love', 'Handmade', 'Bestseller']::text[], '[{"name":"Baby Pink Duo","hex":"#FFB6C1"},{"name":"Pure White Duo","hex":"#FDFBF7"},{"name":"Lavender Duo","hex":"#E6E6FA"}]'::jsonb, 'in_stock', 12, 5, 2, true, '100% Milk Cotton Yarn', '10 cm x 4 cm', null, 30, '2026-01-10T10:00:00.000Z'),
  ('kc-tulip-white-duo', 'pure-white-double-tulip-bell-charm', 'Pure White Double Tulip Bell Charm', array['/images/keychains/tulip_white_duo.jpg']::text[], 'Serene pure ivory white twin tulip blossoms with emerald green crocheted bow and silver key ring.', 'Pure ivory white twin tulip blossoms', 10000, 12000, 'keychain', 'tulip', array['Classic White', 'Handmade']::text[], '[{"name":"Pure White Duo","hex":"#FFFFFF"},{"name":"Baby Pink Duo","hex":"#FFB6C1"}]'::jsonb, 'in_stock', 10, 5, 2, true, '100% Pure Cotton', '10 cm x 4 cm', null, 40, '2026-01-11T10:00:00.000Z'),
  ('kc-tulip-coral-duo', 'coral-red-twin-tulip-bell-charm', 'Coral Red Twin Tulip Bell Charm', array['/images/keychains/tulip_coral_duo.jpg']::text[], 'Bright cheerful coral red twin tulip bells suspended from a hand-crocheted green vine stem.', 'Bright cheerful coral red twin tulip bells', 10000, 12000, 'keychain', 'tulip', array['Bright Bloom', 'Handmade']::text[], '[{"name":"Coral Red Duo","hex":"#FF6F61"},{"name":"Crimson Red Duo","hex":"#DC143C"}]'::jsonb, 'in_stock', 8, 5, 2, true, 'Fine Milk Cotton', '10 cm x 4 cm', null, 50, '2026-01-12T10:00:00.000Z'),
  ('kc-tulip-white-magenta', 'white-magenta-tulip-bell-pair', 'White & Magenta Tulip Bell Pair', array['/images/keychains/tulip_white_magenta_duo.jpg']::text[], 'Two-tone handcrafted twin tulip bells in pure white and vibrant magenta pink, suspended from a green hand-crocheted stem and leaf.', 'Two-tone white & vibrant magenta tulip bells', 10000, 12000, 'keychain', 'tulip', array['Bestseller', 'Handmade', 'Two-Tone']::text[], '[{"name":"White & Magenta Pink","hex":"#E0115F"},{"name":"White & Baby Pink","hex":"#FFB6C1"}]'::jsonb, 'in_stock', 15, 5, 2, true, '100% Milk Cotton Yarn', '10 cm x 4 cm', null, 60, '2026-01-14T10:00:00.000Z'),
  ('kc-tulip-magenta-duo', 'magenta-bloom-double-tulip-keychain', 'Magenta Bloom Double Tulip Keychain', array['/images/keychains/tulip_magenta_duo.jpg']::text[], 'Vibrant matching pair of magenta pink crochet tulip bells with delicate scalloped edges and sage green leaf bow.', 'Magenta pink double tulip bells', 10000, 12000, 'keychain', 'tulip', array['Twin Bells', 'Handmade']::text[], '[{"name":"Magenta Pink Duo","hex":"#D10068"}]'::jsonb, 'in_stock', 9, 5, 2, true, '100% Pure Cotton', '10 cm x 4 cm', null, 70, '2026-01-15T10:00:00.000Z'),
  ('kc-tulip-blue-duo', 'sky-blue-twin-tulip-bell-charm', 'Sky Blue Twin Tulip Bell Charm', array['/images/keychains/tulip_blue_duo.jpg']::text[], 'Refreshing ocean sky blue twin tulip blossoms handcrafted with milk cotton yarn, complete with a silver key ring.', 'Ocean sky blue twin tulip blossoms', 10000, 12000, 'keychain', 'tulip', array['Calm Tones', 'Handmade']::text[], '[{"name":"Sky Blue Duo","hex":"#87CEEB"}]'::jsonb, 'in_stock', 7, 5, 2, true, 'Fine Milk Cotton', '10 cm x 4 cm', null, 80, '2026-01-16T10:00:00.000Z'),
  ('kc-tulip-lavender-duo', 'lavender-lilac-double-tulip-bell-charm', 'Lavender Lilac Double Tulip Bell Charm', array['/images/keychains/tulip_lavender_duo.jpg']::text[], 'Dreamy lavender purple double tulip bells with hand-stitched green stem. Adds cottagecore elegance to your keys or tote bag.', 'Lavender lilac double tulip bells', 10000, 12000, 'keychain', 'tulip', array['Pastel Vibes', 'Handmade', 'New']::text[], '[{"name":"Lavender Lilac Duo","hex":"#BDB0D0"}]'::jsonb, 'in_stock', 11, 5, 2, true, '100% Soft Milk Cotton', '10 cm x 4 cm', null, 90, '2026-01-18T10:00:00.000Z'),
  ('kc-tulip-red-duo', 'crimson-red-double-tulip-bell-keychain', 'Crimson Red Double Tulip Bell Keychain', array['/images/keychains/tulip_red_duo.jpg']::text[], 'Classic romantic crimson red double tulip bells with emerald green crochet stem and silver clasp.', 'Romantic crimson red double tulip bells', 10000, 12000, 'keychain', 'tulip', array['Romantic', 'Handmade']::text[], '[{"name":"Crimson Red Duo","hex":"#C41E3A"}]'::jsonb, 'in_stock', 8, 5, 2, true, '100% Pure Milk Cotton', '10 cm x 4 cm', null, 100, '2026-01-20T10:00:00.000Z'),
  ('kc-daisy-yellow-white', 'sunny-yellow-white-daisy-charm', 'Sunny Yellow & White Daisy Charm', array['/images/keychains/daisy_yellow_white.jpg']::text[], 'Handcrafted iconic cottagecore daisy charm with sunny golden center and pure white blooming scalloped petals.', 'Classic sunny yellow & white cottagecore daisy', 8500, 10000, 'keychain', 'daisy', array['Bestseller', 'Handmade', 'Cottagecore']::text[], '[{"name":"Sunny Yellow & White","hex":"#FFD700"}]'::jsonb, 'in_stock', 14, 5, 2, true, '100% Pure Milk Cotton', '6.5 cm x 6.5 cm', null, 110, '2026-01-05T10:00:00.000Z'),
  ('kc-daisy-purple-lavender', 'royal-purple-lavender-daisy-charm', 'Royal Purple & Lavender Daisy Charm', array['/images/keychains/daisy_purple_lavender.jpg']::text[], 'Two-tone floral daisy charm featuring deep royal purple scalloped petals and a soft lavender center disc.', 'Deep royal purple petals & soft lavender center', 8500, 10000, 'keychain', 'daisy', array['Two-Tone', 'Handmade']::text[], '[{"name":"Royal Purple & Soft Lavender","hex":"#7851A9"}]'::jsonb, 'in_stock', 6, 5, 2, true, '100% Milk Cotton Yarn', '6.5 cm x 6.5 cm', null, 120, '2026-01-06T10:00:00.000Z'),
  ('kc-daisy-purple-white', 'royal-purple-white-daisy-charm', 'Royal Purple & White Daisy Charm', array['/images/keychains/daisy_purple_white.jpg']::text[], 'Stunning contrast daisy keychain crafted with deep purple center and crisp white layered petals.', 'Contrast deep purple center with crisp white petals', 8500, 10000, 'keychain', 'daisy', array['Contrast Edit', 'Handmade']::text[], '[{"name":"White & Royal Purple","hex":"#4B0082"}]'::jsonb, 'in_stock', 10, 5, 2, true, '100% Pure Cotton', '6.5 cm x 6.5 cm', null, 130, '2026-01-07T10:00:00.000Z'),
  ('kc-daisy-magenta-white', 'magenta-white-daisy-charm', 'Magenta & White Daisy Charm', array['/images/keychains/daisy_magenta_white.jpg']::text[], 'Handcrafted blooming daisy keychain featuring bold magenta petals, pure white circular center, and silver keyring.', 'Bold magenta petals with pure white circular core', 8500, 10000, 'keychain', 'daisy', array['Bestseller', 'Handmade']::text[], '[{"name":"Magenta Pink & White","hex":"#FF007F"}]'::jsonb, 'in_stock', 12, 5, 2, true, '100% Soft Milk Cotton', '6.5 cm x 6.5 cm', null, 140, '2026-01-08T10:00:00.000Z'),
  ('kc-daisy-pink-twotone', 'pastel-two-tone-pink-daisy-charm', 'Pastel Two-Tone Pink Daisy Charm', array['/images/keychains/daisy_pink_twotone.jpg']::text[], 'Sweet double-pink crochet daisy with soft pastel blush petals surrounding a bright candy pink core.', 'Pastel blush petals surrounding candy pink core', 8500, 10000, 'keychain', 'daisy', array['Two-Tone', 'Cottagecore']::text[], '[{"name":"Pastel Pink & Candy Pink","hex":"#FF69B4"}]'::jsonb, 'in_stock', 9, 5, 2, true, '100% Milk Cotton Yarn', '6.5 cm x 6.5 cm', null, 150, '2026-01-09T10:00:00.000Z'),
  ('kc-daisy-red-white', 'crimson-red-white-daisy-charm', 'Crimson Red & White Daisy Charm', array['/images/keychains/daisy_red_white.jpg']::text[], 'Vibrant crimson red petals with a clean white crocheted center disk and sturdy silver chain attachment.', 'Vibrant crimson red petals with white disk', 8500, 10000, 'keychain', 'daisy', array['Classic Charm', 'Handmade']::text[], '[{"name":"Crimson Red & White","hex":"#D2143A"}]'::jsonb, 'in_stock', 8, 5, 2, true, '100% Pure Cotton', '6.5 cm x 6.5 cm', null, 160, '2026-01-10T10:00:00.000Z'),
  ('kc-daisy-sky-blue', 'sky-blue-white-daisy-charm', 'Sky Blue & White Daisy Charm', array['/images/keychains/daisy_sky_blue.jpg']::text[], 'Refreshing ocean sky blue crochet petals framing a pure white stitched center. Calming and cheerful aesthetic.', 'Ocean sky blue petals framing pure white center', 8500, 10000, 'keychain', 'daisy', array['Calm Tones', 'Aesthetic']::text[], '[{"name":"Sky Blue & White","hex":"#87CEEB"}]'::jsonb, 'in_stock', 10, 5, 2, true, 'Fine Milk Cotton', '6.5 cm x 6.5 cm', null, 170, '2026-01-12T10:00:00.000Z'),
  ('kc-daisy-pink-purple', 'pastel-pink-royal-purple-daisy-charm', 'Pastel Pink & Royal Purple Daisy Charm', array['/images/keychains/daisy_pink_purple.jpg']::text[], 'Charming color combination of delicate baby pink textured petals with an intricate royal purple seed core.', 'Baby pink textured petals with royal purple center', 8500, 10000, 'keychain', 'daisy', array['Unique Color', 'Handmade']::text[], '[{"name":"Baby Pink & Royal Purple","hex":"#9370DB"}]'::jsonb, 'in_stock', 7, 5, 2, true, '100% Milk Cotton Yarn', '6.5 cm x 6.5 cm', null, 180, '2026-01-13T10:00:00.000Z'),
  ('kc-rose-magenta', 'magenta-rose-bloom-charm', 'Magenta Rose Bloom Charm', array['/images/keychains/rose_magenta.jpg']::text[], 'Vibrant handmade hot pink magenta crochet rose charm with tender green leaf calyx and sturdy silver key ring.', 'Vibrant magenta crochet rose charm with green leaf', 10000, 12000, 'keychain', 'rose', array['Bestseller', 'Romantic', 'Handmade']::text[], '[{"name":"Magenta Pink","hex":"#E0115F"}]'::jsonb, 'in_stock', 8, 5, 2, true, '100% Soft Milk Cotton', '6 cm x 4 cm', null, 190, '2026-01-01T10:00:00.000Z'),
  ('kc-rose-pink', 'pastel-baby-pink-rose-charm', 'Pastel Baby Pink Rose Charm', array['/images/keychains/rose_pink.jpg']::text[], 'Soft pastel baby pink spiral rose charm crocheted with ultra-soft milk cotton yarn and silver keychain attachment.', 'Pastel baby pink spiral rose charm', 10000, 12000, 'keychain', 'rose', array['Pastel Love', 'Romantic', 'Handmade']::text[], '[{"name":"Baby Pink","hex":"#FFB6C1"}]'::jsonb, 'in_stock', 6, 5, 2, true, '100% Milk Cotton Yarn', '6 cm x 4 cm', null, 200, '2026-01-02T10:00:00.000Z'),
  ('kc-rose-purple', 'royal-purple-rose-charm', 'Royal Purple Rose Charm', array['/images/keychains/rose_purple.jpg']::text[], 'Rich vivid royal purple spiral rose charm handcrafted with layered petals and silver key ring.', 'Royal purple spiral rose charm', 10000, 12000, 'keychain', 'rose', array['Royal Edition', 'Handmade']::text[], '[{"name":"Royal Purple","hex":"#7B1FA2"}]'::jsonb, 'in_stock', 5, 5, 2, true, '100% Milk Cotton Yarn', '6 cm x 4 cm', null, 210, '2026-01-03T10:00:00.000Z'),
  ('kc-rose-white', 'pure-white-rosebud-charm', 'Pure White Rosebud Charm', array['/images/keychains/rose_white.jpg']::text[], 'Pristine pure white handcrafted crochet rose charm with elegant petal swirl and silver keyring.', 'Pristine pure white crochet rose charm', 10000, 12000, 'keychain', 'rose', array['Classic White', 'Minimalist', 'Handmade']::text[], '[{"name":"Pure White","hex":"#FFFFFF"}]'::jsonb, 'in_stock', 7, 5, 2, true, '100% Pure Cotton', '6 cm x 4 cm', null, 220, '2026-01-04T10:00:00.000Z'),
  ('kc-evil-eye', 'evil-eye-nazar-protection-charm', 'Evil Eye Keychain', array['/images/keychains/evil_eye_amulet.jpg']::text[], 'Handcrafted royal blue and sky blue circular Evil Eye crochet talisman with key ring. A protective and aesthetic everyday charm.', 'Protective blue circular Evil Eye talisman', 10000, 12000, 'keychain', 'others', array['Evil Eye', 'Protection Charm', 'Handmade']::text[], '[{"name":"Royal Blue & Sky Blue","hex":"#002366"}]'::jsonb, 'in_stock', 14, 5, 2, true, '100% Premium Milk Cotton', '6 cm x 6 cm', null, 230, '2026-01-18T10:00:00.000Z'),
  ('kc-sunflower-orange', 'sunflower-keychain-amber-core', 'Sunflower Keychain', array['/images/keychains/sunflower_orange.jpg']::text[], 'Cheerful handmade sunflower keychain with bright yellow petals, warm amber-orange center, and golden key ring.', 'Cheerful sunflower with warm amber core', 8500, 10000, 'keychain', 'others', array['Sunflower', 'Handmade', 'Bestseller']::text[], '[{"name":"Golden Yellow & Orange","hex":"#FFA500"}]'::jsonb, 'in_stock', 12, 5, 2, true, '100% Breathable Cotton', '7 cm x 7 cm', null, 240, '2026-01-16T10:00:00.000Z'),
  ('kc-sunflower-brown', 'classic-sunflower-keychain-dark-core', 'Sunflower Keychain (Classic Dark Core)', array['/images/keychains/sunflower_brown.jpg']::text[], 'Hand-stitched radiant yellow sunflower keychain featuring a rich dark chocolate textured seed center and sturdy keyring.', 'Radiant yellow sunflower with dark chocolate core', 8500, 10000, 'keychain', 'others', array['Sunflower', 'Cottagecore']::text[], '[{"name":"Yellow & Dark Brown","hex":"#5C4033"}]'::jsonb, 'in_stock', 10, 5, 2, true, '100% Soft Cotton', '7 cm x 7 cm', null, 250, '2026-01-17T10:00:00.000Z'),
  ('kc-spiderman', 'hanging-spiderman-crochet-charm', 'Spider-Man Keychain', array['/images/keychains/spiderman_hanging.jpg']::text[], 'Handcrafted upside-down hanging Spider-Man crochet amigurumi with white cord for bags, keys, or rearview mirrors.', 'Upside-down hanging Spider-Man amigurumi', 30000, 35000, 'keychain', 'others', array['Spider-Man', 'Bestseller', 'Handmade', 'Fan Favorite']::text[], '[{"name":"Classic Red & Blue","hex":"#D21034"}]'::jsonb, 'in_stock', 15, 5, 3, true, '100% Soft Milk Cotton Yarn', '8 cm x 4 cm', null, 260, '2026-01-15T10:00:00.000Z'),
  ('bq-ocean-lily', 'ocean-breeze-lily-bouquet', 'Ocean Breeze Lily & Daisy Bouquet', array['/images/bouquets/ocean-blue-lily-bouquet.png']::text[], 'An enchanting bouquet of handcrafted powder blue crochet lilies accented with delicate chamomile daisies and cheerful yellow stamens, wrapped in ice blue paper and tied with a sunny yellow satin ribbon.', 'Sky-blue crochet lilies & daisies in ice blue wrap', 58000, 69900, 'bouquet', null, array['Bestseller', 'Ocean Breeze', 'Everlasting', 'Handmade']::text[], '[{"name":"Sky Blue & White","hex":"#64B5F6"},{"name":"Pastel Lilac","hex":"#CE93D8"}]'::jsonb, 'made_to_order', 15, 3, 3, true, 'Premium Milk Cotton Yarn', 'Approx. 30 cm height', '3 Blue Lilies + 3 Daisies + Foliage', 270, '2026-01-01T10:00:00.000Z'),
  ('bq-grand-tulips', 'grand-tulip-blossom-luxury-bouquet', 'Grand Spring Tulip & Blossom Luxury Bouquet', array['/images/bouquets/grand-tulip-blossom-bouquet.jpg']::text[], 'A magnificent, full-blooming luxury bouquet overflowing with handcrafted purple, lavender, pink, and cream tulips, paired with blossoming cherry branches and lavender sprigs. Wrapped in soft pink paper with an elegant black bow.', 'Grand luxury bouquet with tulips & cherry blossoms', 250000, 289900, 'bouquet', null, array['Luxury Edition', 'Grand Bouquet', 'Special Occasion']::text[], '[{"name":"Spring Pastel Garden","hex":"#CE93D8"},{"name":"Rosy Pink Harmony","hex":"#F48FB1"}]'::jsonb, 'made_to_order', 8, 2, 6, true, '100% Ultra-Soft Milk Cotton', 'Approx. 45 cm height', '12+ Stems (Tulips, Blossoms, Lavender)', 280, '2026-01-02T10:00:00.000Z'),
  ('bq-happiness-mix', 'little-bouquet-of-happiness', 'Little Bouquet of Happiness', array['/images/bouquets/little-bouquet-of-happiness.jpg']::text[], 'A cheerful medley of handcrafted crochet blooms including royal blue roses, soft yellow puffs, lavender sprigs, and dainty sky-blue forget-me-nots wrapped in layered blue paper with a pure white ribbon.', 'Handcrafted bouquet of happiness with mixed blooms', 90000, 109900, 'bouquet', null, array['Little Bouquet of Happiness', 'Vibrant', 'Handmade with Love']::text[], '[{"name":"Happiness Multi-Mix","hex":"#1E88E5"},{"name":"Sunshine Meadow","hex":"#FDD835"}]'::jsonb, 'made_to_order', 18, 3, 3, true, 'Fine Combed Milk Cotton', 'Approx. 28 cm height', '6 Mixed Handcrafted Stems', 290, '2026-01-03T10:00:00.000Z'),
  ('bq-spiderman-tulip', 'spiderman-red-tulip-bouquet', 'Spidey & Red Tulip Special Bouquet', array['/images/bouquets/spiderman-tulip-bouquet.png']::text[], 'The perfect quirky & romantic gift featuring an adorable crochet Spider-Man mini figure accompanied by a rich crimson tulip and delicate baby''s breath accents, wrapped in sleek modern monochrome wrapping with a white satin ribbon.', 'Crochet Spider-Man & crimson tulip in modern wrap', 98000, 119900, 'bouquet', null, array['Character Edition', 'Spidey Special', 'Cute & Quirky']::text[], '[{"name":"Classic Spidey Red & Blue","hex":"#E53935"}]'::jsonb, 'made_to_order', 12, 3, 4, true, 'Soft Acrylic & Milk Cotton Blend', 'Approx. 32 cm height', '1 Spider-Man Doll + 1 Tulip + Baby''s Breath', 300, '2026-01-04T10:00:00.000Z'),
  ('bq-love-you', 'i-love-you-heart-bouquet', 'I Heart U Forever Keepsake Bouquet', array['/images/bouquets/i-love-you-heart-bouquet.jpg']::text[], 'An adorable and heartfelt romantic token featuring three crochet stems spelling out "I ❤️ U" with pure white letters and a plump ruby red heart, wrapped in rustic kraft paper and tied with a delicate white bow.', '3 crochet stems spelling "I ❤️ U" in kraft wrap', 60000, 75000, 'bouquet', null, array['Romantic', 'I Love You', 'Anniversary Favorite', 'Minimalist']::text[], '[{"name":"Ruby Heart & White Letters","hex":"#D32F2F"}]'::jsonb, 'made_to_order', 20, 4, 2, true, '100% Natural Cotton Yarn', 'Approx. 25 cm height', '3 Stems (Letter I, Heart, Letter U)', 310, '2026-01-05T10:00:00.000Z')
on conflict (id) do nothing;

insert into public.coupons (code, type, discount_value, min_order_paise, description) values
  ('BLOOM10', 'percentage', 10, 40000, '10% off on handmade orders above ₹400'),
  ('WELCOME50', 'flat', 5000, 30000, 'Flat ₹50 welcome discount for your first crochet piece'),
  ('VALENTINE15', 'percentage', 15, 60000, '15% special celebration discount on bouquets & charms')
on conflict (code) do nothing;
