import QRCode from 'qrcode';
import { siteConfig } from '../../config/site.config';

/**
 * Official Google Pay QR cards for the two keychain prices (₹85 and ₹100). They are
 * pre-generated by Google Pay for the store's UPI ID with the amount locked in.
 */
export const OFFICIAL_QR_BY_PAISE: Record<number, string> = {
  8500: '/images/Pay/upi-qr-85.jpg',
  10000: '/images/Pay/upi-qr-100.jpg',
};

/** Standard UPI deep link (NPCI spec) for the store's UPI ID and the exact amount. */
export function buildUpiLink(amountPaise: number, note = 'BloomCraft Order'): string {
  const params = new URLSearchParams({
    pa: siteConfig.upiId,
    pn: siteConfig.upiPayeeName,
    am: (amountPaise / 100).toFixed(2),
    cu: 'INR',
    tn: note,
  });
  return `upi://pay?${params.toString()}`;
}

/** A real, scannable QR for any other total (same UPI ID, amount pre-filled). */
export function upiQrDataUrl(link: string): Promise<string> {
  return QRCode.toDataURL(link, {
    width: 400,
    margin: 1,
    errorCorrectionLevel: 'M',
    color: { dark: '#000000', light: '#FFFFFF' },
  });
}

/** UPI transaction references (UTR / RRN) are 12 digits. */
export const UTR_PATTERN = /^\d{12}$/;

export interface UpiApp {
  id: string;
  name: string;
  short: string;
  bg: string;
}

export const UPI_APPS: UpiApp[] = [
  { id: 'gpay', name: 'Google Pay', short: 'G', bg: '#4285F4' },
  { id: 'phonepe', name: 'PhonePe', short: 'Pe', bg: '#5F259F' },
  { id: 'paytm', name: 'Paytm', short: 'P', bg: '#00BAF2' },
  { id: 'bhim', name: 'BHIM UPI', short: 'B', bg: '#F47920' },
];
